source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
use_frameworks!

pod 'SwiftHTTP', '~> 1.0.0'
pod 'JSONJoy-Swift', '~> 1.0.0'
pod 'GoogleMaps', '~> 1.11.1’

pod 'AWSiOSSDKv2'
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'

post_install do |installer|
    `find Pods -regex 'Pods/Google.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)GoogleMaps\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
target 'LetsGo' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.0'
end

